version: '3.8'

services:
  payments-stripe:
    build:
      context: ./services/payments-stripe
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
    env_file:
      - .env
    volumes:
      - ./services/payments-stripe:/app
      - /app/node_modules
    depends_on:


  notifications:
    build:
      context: ./services/notifications
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
    env_file:
      - .env
    volumes:
      - ./services/notifications:/app
      - /app/node_modules
    depends_on:


  file-storage:
    build:
      context: ./services/file-storage
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
    env_file:
      - .env
    volumes:
      - ./services/file-storage:/app
      - /app/node_modules
    depends_on:


  analytics:
    build:
      context: ./services/analytics
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - PORT=3005
    env_file:
      - .env
    volumes:
      - ./services/analytics:/app
      - /app/node_modules
    depends_on:


volumes:
  postgres_data:
  redis_data:
